import { useState } from 'react';
import { Search, ChevronDown } from 'lucide-react';
import { questionSections, type Question, type Report } from '../../../shared/interview';
export function QuestionCard({question,index}:{question:Question;index:number}) {return <details className="question"><summary><span className="question-number">{String(index+1).padStart(2,'0')}</span><span><span className="question-meta">{question.category} <span>·</span> {question.difficulty}</span><strong>{question.question}</strong></span><ChevronDown className="disclosure" size={19}/></summary><div className="answer"><p className="relevance">{question.relevance}</p>{[['Detailed answer',question.answer],['Simple explanation',question.simpleExplanation],['Practical example',question.practicalExample]].map(([title,body])=><section key={title}><h4>{title}</h4><p>{body}</p></section>)}<section><h4>Common mistakes</h4><ul>{question.commonMistakes.map(value=><li key={value}>{value}</li>)}</ul></section><section><h4>Follow-up questions</h4><ul>{question.followUpQuestions.map(value=><li key={value}>{value}</li>)}</ul></section></div></details>;}
export function Questions({report}:{report:Report}) {
  const [category,setCategory]=useState('All');const [search,setSearch]=useState('');
  const all=questionSections.flatMap(([key,label])=>report[key].map(question=>({...question,section:label})));
  const filtered=all.filter(q=>(category==='All'||q.section===category)&&`${q.question} ${q.answer} ${q.category}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="questions-section"><div className="section-heading"><div><span className="eyebrow">PRACTICE WITH PURPOSE</span><h2>Your interview questions <span className="count">{all.length}</span></h2></div><label className="search"><Search size={18}/><input aria-label="Search interview questions" placeholder="Search interview questions…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="filter-row" role="group" aria-label="Filter questions by category">{['All',...questionSections.map(([,label])=>label)].map(label=><button type="button" key={label} aria-pressed={category===label} className={category===label?'selected':''} onClick={()=>setCategory(label)}>{label}</button>)}</div><p className="muted small" aria-live="polite">{filtered.length} questions · Select a question to explore the answer</p><div className="question-list">{filtered.map((q,i)=><QuestionCard key={q.question} question={q} index={i}/>)}{!filtered.length&&<div className="empty-search"><h3>No questions found</h3><p>Try another search or category.</p><button className="button secondary" onClick={()=>{setSearch('');setCategory('All');}}>Clear filters</button></div>}</div></section>;
}
