import { ArrowRight, FileText, List, Sparkles, Gift } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ResumeForm } from '../components/ResumeForm';
import { Stepper } from '../components/Layout';
import { LoadingState } from '../components/Feedback';
import type { Submission } from '../../../shared/interview';
export function HomePage({onSubmit,error,busy,initial}:{onSubmit:(input:Submission)=>void;error:string;busy:boolean;initial?:Submission}) {
  return <div className="container"><section className="hero"><h1>Prepare smarter.<br/><span>Interview better.</span></h1><p>Turn your resume and job description into a personalized interview preparation plan.</p><Link to="/sample" className="text-link">Explore a sample report <ArrowRight size={16}/></Link></section><Stepper/><div className="workspace" id="start">{busy?<div className="form-panel"><LoadingState/></div>:<ResumeForm onSubmit={onSubmit} error={error} initial={initial}/>}<aside className="benefits" id="features"><h2>Less guesswork.<br/><span>More confidence.</span></h2><ol>{[['Know where you stand','Get a clear analysis of your strengths, missing skills, and key interview topics.'],['Focus on what matters','Receive a tailored plan with the most relevant areas to study and practice.'],['Walk in prepared','Go into your interview with structured practice and greater confidence.']].map(([title,body],i)=><li key={title}><span className="number">{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol><div className="free-note"><Gift/><div><strong>Free to start. No account needed.</strong><p>Get your personalized analysis in minutes.</p></div></div></aside></div><section className="how-it-works" id="how-it-works"><div><small>HOW IT WORKS</small><h3>From your materials<br/>to a smarter plan.</h3></div>{[[FileText,'Upload your resume','Share your resume (PDF or TXT).'],[List,'Add the job description','Paste the complete job description for your target role.'],[Sparkles,'Get your personalized plan','Receive a skill-gap analysis and a tailored interview preparation plan.']].map(([Icon,title,body])=>{const Component=Icon as typeof FileText;return <div className="how-step" key={title as string}><span className="icon-bubble"><Component/></span><div><h4>{title as string}</h4><p>{body as string}</p></div></div>;})}</section></div>;
}
