import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Check, ArrowLeft, ArrowUpRight, Sparkles, LockKeyhole } from 'lucide-react';
import type { AppConfig } from '../services/api';
import { ErrorMessage, LoadingState } from '../components/Feedback';
export function PaymentPage({config,configLoading,onRetryConfig,canGenerate,onGenerate,busy,error}:{config:AppConfig|null;configLoading:boolean;onRetryConfig:()=>void;canGenerate:boolean;onGenerate:(code:string)=>void;busy:boolean;error:string}) {
 const [code,setCode]=useState('');
 return <div className="container pricing-page"><Link to={canGenerate?'/analysis':'/'} className="back-link"><ArrowLeft size={16}/> {canGenerate?'Back to your analysis':'Back to home'}</Link><div className="page-heading centered"><h1>A small step.<br/><span>A more prepared you.</span></h1><p>Invest in focused preparation for the role you really want.</p></div>{busy?<LoadingState full/>:<div className="pricing-card"><span className="icon-bubble"><Sparkles/></span><h2>Unlock Full Interview Pack</h2><p className="muted">One role. One plan. All the preparation you need.</p><div className="price">₹199 <span>one-time payment</span></div><ul>{['Personalized interview questions for your role','40+ questions for the complete Java track','Detailed answers & practical examples','Resume-based & system-design questions','7-day preparation plan','Downloadable PDF to study anywhere'].map(value=><li key={value}><Check size={18}/>{value}</li>)}</ul>{configLoading?<p role="status">Loading payment configuration…</p>:!config?<><ErrorMessage message="Unable to load payment configuration. Check the backend connection and try again."/><button className="button secondary full-width" onClick={onRetryConfig}>Retry connection</button></>:!canGenerate?<Link to="/" className="button primary full-width">Start with your free analysis</Link>:config.premiumMode?<><a className={`button primary full-width ${!config.paymentLink?'disabled-link':''}`} href={config.paymentLink||undefined} target="_blank" rel="noopener noreferrer" aria-disabled={!config.paymentLink}>Unlock Full Report — ₹199 <ArrowUpRight size={17}/></a>{!config.paymentLink&&<p className="muted small">Payment is not configured yet. Please contact the operator.</p>}<p className="small muted">After payment, the operator verifies your payment and provides an access code. Payment does not unlock the pack automatically.</p><form onSubmit={e=>{e.preventDefault();onGenerate(code);}} className="redeem-form"><label htmlFor="access">Already paid? Enter your access code</label><input id="access" type="password" required value={code} onChange={e=>setCode(e.target.value)} autoComplete="off"/><button className="button secondary full-width">Generate my interview pack</button></form></>:<><div className="dev-note">Local development mode · No payment required</div><button className="button primary full-width" onClick={()=>onGenerate('')}>Generate Full Interview Pack <Sparkles size={17}/></button></>}{error&&<ErrorMessage message={error}/>}<p className="privacy-line"><LockKeyhole size={13}/> Your resume is never permanently stored.</p></div>}</div>;
}
