import { useEffect, useRef, useState } from 'react';
import { Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import type { Analysis, Report, Submission } from '../../shared/interview';
import { Layout } from './components/Layout';
import { HomePage } from './pages/HomePage';
import { AnalysisPage } from './pages/AnalysisPage';
import { PremiumReportPage } from './pages/PremiumReportPage';
import { PaymentPage } from './pages/PaymentPage';
import { sampleReport, sampleRole, sampleExperience } from './data/sample';
import { generate, getConfig, type AppConfig } from './services/api';
export default function App(){
 const navigate=useNavigate();const [input,setInput]=useState<Submission>();const [analysis,setAnalysis]=useState<Analysis>();const [report,setReport]=useState<Report>();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [config,setConfig]=useState<AppConfig|null>(null);
 const [configLoading,setConfigLoading]=useState(true);
 const generating=useRef(false);
 async function loadConfig(){setConfigLoading(true);try{setConfig(await getConfig());}catch{setConfig(null);}finally{setConfigLoading(false);}}
 useEffect(()=>{void loadConfig();},[]);
 async function analyze(data:Submission){if(generating.current)return;generating.current=true;setInput(data);setBusy(true);setError('');setReport(undefined);setAnalysis(undefined);try{setAnalysis(await generate<Analysis>(data));navigate('/analysis');}catch(e){setError(e instanceof Error?e.message:'Unable to generate your analysis.');}finally{generating.current=false;setBusy(false);}}
 async function full(code:string){if(!input||!analysis||generating.current)return;generating.current=true;setBusy(true);setError('');try{setReport(await generate<Report>(input,true,code));navigate('/report');}catch(e){setError(e instanceof Error?e.message:'Unable to generate your report.');}finally{generating.current=false;setBusy(false);}}
 return <Layout><Routes><Route path="/" element={<HomePage onSubmit={data=>void analyze(data)} initial={input} error={error} busy={busy}/>}/><Route path="/analysis" element={analysis&&input?<AnalysisPage analysis={analysis} role={input.targetRole}/>:<Navigate to="/" replace/>}/><Route path="/report" element={report&&input?<PremiumReportPage report={report} role={input.targetRole} experience={input.experience}/>:<Navigate to="/" replace/>}/><Route path="/sample" element={<PremiumReportPage report={sampleReport} role={sampleRole} experience={sampleExperience} sample/>}/><Route path="/pricing" element={<PaymentPage configLoading={configLoading} onRetryConfig={()=>void loadConfig()} config={config} canGenerate={Boolean(analysis&&input)} onGenerate={code=>void full(code)} busy={busy} error={error}/>}/><Route path="/privacy" element={<div className="container prose"><h1>Your privacy matters.</h1><p>Your resume is processed only to generate your interview analysis. Uploaded files are not permanently stored by this application.</p><h2>What happens to your data</h2><p>The server reads your PDF or TXT file in memory. Extracted resume text, your job description, target role, and experience are sent to Google Gemini for analysis. Google's API data policies apply to that processing; review the provider terms before submitting sensitive information.</p><p>We do not use a database, save resume files, or log their contents. Reports and uploaded files remain in browser memory during your session. Refreshing or closing the page clears the application's session state. Downloaded PDFs stay on your device.</p><h2>Keep your submission focused</h2><p>Remove contact details and other information that is unnecessary for interview preparation. Do not submit confidential employer or client information.</p><h2>Service protection</h2><p>The backend temporarily holds request counts by IP address to limit abuse. Hosting and AI providers may maintain their own operational logs under their policies.</p><Link to="/" className="button primary">Back to your preparation</Link></div>}/><Route path="*" element={<div className="container prose"><h1>Page not found.</h1><Link className="button primary" to="/">Return home</Link></div>}/></Routes></Layout>;
}
