import { questionSections, type Report } from '../../../shared/interview';
export async function downloadReport(report:Report,role:string,experience:string,sample=false){
 const {jsPDF}=await import('jspdf');
 const doc=new jsPDF();let y=25;const width=172;
 const clean=(s:string)=>s.replace(/[–—]/g,'-').replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/…/g,'...');
 function write(value:string,size=10,bold=false){doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);const lines=doc.splitTextToSize(clean(value),width) as string[];for(const line of lines){if(y>275){doc.addPage();y=24;}doc.text(line,19,y);y+=size*0.48;}y+=3;}
 function heading(title:string){if(y>252){doc.addPage();y=24;}y+=5;doc.setTextColor(80,70,229);write(title,15,true);doc.setTextColor(25,30,48);}
 write('InterviewPrep AI',24,true);write(sample?'SAMPLE INTERVIEW PACK — illustrative content':'PERSONALIZED INTERVIEW PACK',10,true);write(role,18,true);write(`Experience: ${experience}`);write(`Generated: ${new Date().toLocaleDateString()}`);heading('Your estimated resume-to-JD match');write(`${report.matchScore}% — an estimate, not a hiring probability.`,13,true);write(report.candidateSummary);write(report.matchExplanation);heading('Strong skills');write(report.strongSkills.join(' · '));heading('Skill gaps');write(report.missingSkills.join(' · '));heading('Priority topics');report.priorityTopics.forEach((v,i)=>write(`${i+1}. ${v}`));heading('Most likely questions');report.mostLikelyQuestions.forEach((v,i)=>write(`${i+1}. ${v}`));
 for(const [key,label] of questionSections){if(!report[key].length)continue;heading(`${label} questions`);for(const [i,q] of report[key].entries()){write(`${i+1}. ${q.question}`,12,true);write(`${q.category} | ${q.difficulty}`);for(const [title,body] of [['Why it matters',q.relevance],['Detailed answer',q.answer],['Simple explanation',q.simpleExplanation],['Practical example',q.practicalExample],['Common mistakes',q.commonMistakes.map(s=>`- ${s}`).join('\n')],['Follow-up questions',q.followUpQuestions.map(s=>`- ${s}`).join('\n')]]){write(title,10,true);write(body);}}}
 heading('Your 7-day preparation plan');for(const day of report.studyPlan){write(`Day ${day.day}: ${day.title}`,12,true);day.tasks.forEach(task=>write(`- ${task}`));}
 const total=doc.getNumberOfPages();for(let page=1;page<=total;page++){doc.setPage(page);doc.setFontSize(8);doc.setTextColor(110);doc.text('InterviewPrep AI | Private preparation material',19,289);doc.text(`${page} / ${total}`,190,289,{align:'right'});}doc.save(`InterviewPrep-${sample?'sample-':''}${role.replace(/[^a-zA-Z0-9]/g,'-')}.pdf`);
}
